DROP TABLE IF EXISTS People CASCADE;
DROP TABLE IF EXISTS Observation CASCADE;
DROP TABLE IF EXISTS Cosmic_event CASCADE;
DROP TABLE IF EXISTS Planet CASCADE;
DROP TABLE IF EXISTS Room CASCADE;
DROP TABLE IF EXISTS Device CASCADE;
DROP TABLE IF EXISTS Behaviour CASCADE;
DROP TABLE IF EXISTS Nation CASCADE;
DROP TABLE IF EXISTS Interaction CASCADE;

DROP TYPE IF EXISTS status;
DROP TYPE IF EXISTS assessments;
DROP TYPE IF EXISTS sizes;